# Generated by Django 3.2.22 on 2023-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsanctionscheckfailure',
            name='sdn_check_response',
        ),
        migrations.RemoveField(
            model_name='sanctionscheckfailure',
            name='sdn_check_response',
        ),
        migrations.AddField(
            model_name='historicalsanctionscheckfailure',
            name='sanctions_response',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sanctionscheckfailure',
            name='sanctions_response',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsanctionscheckfailure',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalsanctionscheckfailure',
            name='system_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsanctionscheckfailure',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionscheckfailure',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sanctionscheckfailure',
            name='system_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionscheckfailure',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
